### ISSUE TITLE
Better with Mods Compatibility

### ISSUE THREAD

**Issue by stohun01** [KorDum/NotEnoughScaffold#2]
The big holes enchantment is incompatible with the hardcore piles feature of Better with Mods (ie 3 piles that make up 75% of a block drop instead of the block itself when using an improper tool). When harvesting dirt with a shovel that has the enchantment the center block drops as expected but the surrounding 8 drop dirt piles.

**Comment by KorDum** [comment]
Thanks for report! Can you add screenshot?

**Comment by stohun01** [comment]
What do you need to see?

**Comment by KorDum** [comment]
I can't reproduce the problem.
BetterWithMods 2.0.25.
Can you show me more info and screenshots?

![image](https://user-images.githubusercontent.com/1331559/35777575-5ba26308-09c1-11e8-8b08-fa14e8b95a9a.png)

**Comment by KorDum** [comment]
Better with Mods crashes when you view the creative tab or dig dirt by non enchanted shovel...

**Comment by KorDum** [comment]
Ah, sorry, I understood.
Unfortunately, this mod uses its cunning redefinitions of harvester blocks, I do not see the possibility of making compatibility.
You can disable enchantement in config.

**Comment by KorDum** [comment]
Hello!
Can you test v1.8 with BetterWithMods? It should be fixed.
