### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by theshadowake** [KorDum/NotEnoughScaffold#3]
I'm not sure if I'm missing something, but is there any functional difference between standard and reinforced scaffolding (other than needing a pick to break the latter)?

It would be a nice feature if to differentiate them standard scaffold broke automatically and dropped itself after say 30 seconds or a minute. That would be great for just getting up high and not worrying about breaking it from the bottom.

Just an idea :)

**Comment by KorDum** [comment]
Thanks for feedback!
The player can move faster through the iron scaffold. And iron scaffolds can stay in the air longer (see screenshot):

![image](https://user-images.githubusercontent.com/1331559/42644828-2f18e1fc-8605-11e8-803c-03ed15c65c39.png)

![image](https://user-images.githubusercontent.com/1331559/42644842-3b4b4460-8605-11e8-99b5-73369a09e629.png)

> It would be a nice feature if to differentiate them standard scaffold broke automatically and dropped itself after say 30 seconds or a minute. That would be great for just getting up high and not worrying about breaking it from the bottom.

Scaffolds are common blocks without tile entity (for CPU and RAM performance), so nothing beyond the complex these blocks can not :)
