### ISSUE TITLE
Big holes will occasionally go horizontally when mining in a straight line

### ISSUE THREAD

**Issue by futurenp** [KorDum/NotEnoughScaffold#6]

**Comment by KorDum** [comment]
Thanks for feedback!
I can't reproduce this. Can you make video or something?

**Comment by futurenp** [comment]
After testing it seems I am also unable to recreate this, It was happening before, I must have removed a mod that was causing issues with this. Sorry for wasting you time. 
Also can you possibly add a config for the durability penalty of big holes?

**Comment by futurenp** [comment]
It happened again for some reason but I was able to record it
https://drive.google.com/file/d/1cpvizi19Rnet_Upap2CQnM3WXOWRnonu/view?usp=sharing

**Comment by KorDum** [comment]
> Also can you possibly add a config for the durability penalty of big holes?

Do you mean the chance to spend more tool durability than it was dug up?

**Comment by futurenp** [comment]
> Do you mean the chance to spend more tool durability than it was dug up?

Yes

**Comment by KorDum** [comment]
Can you tell me what other enchantments there are on a pickaxe and what version of Forge? I can't reproduce yet...

**Comment by KorDum** [comment]
I tested also with Forge 14.23.5.2838 and latest version 1.9 of mod.

**Comment by futurenp** [comment]
Big holes, mending, efficiency 5, unbreaking 3, fortune 3

It might have something to do with durability? It didn't start happening until it was about 1/3 broken

**Comment by KorDum** [comment]
Very interesting. I created diamond pickaxe with `Big holes, mending, efficiency 5, unbreaking 3, fortune 3` and all ok. Can you test this with Forge + NotEnoughScaffold only? Maybe mod collision or something.

**Comment by futurenp** [comment]
yes

**Comment by futurenp** [comment]
I cannot recreate it with just notenough scaffolding in singleplayer
Maybe it has to do with being on a sever?

**Comment by futurenp** [comment]
I cannot recreate it in single player on the modpack I am playing, I am thinking it has to do with multiplayer

**Comment by KorDum** [comment]
Now I will check.

**Comment by KorDum** [comment]
No, I can't reproduce. Can you dig with your friend at the same time? I think this incorrect behavior is associated with simultaneous digging.

**Comment by KorDum** [comment]
And what is Forge version for server?

**Comment by futurenp** [comment]
14.23.5.2838

**Comment by futurenp** [comment]
I can test tommorow if that is the case

**Comment by KorDum** [comment]
Thanks for the help, I figured it out and will soon make a new build.

**Comment by KorDum** [comment]
Check new penalty mechanics in config (default chance is 0)
